# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: alvinjhson
# "service" is the name of this project. This will also be added to your AWS resource names.
service: AgriServiceLog

provider:
  name: aws
  runtime: nodejs20.x
  profile: test
  region: eu-north-1
  stage: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::225989356862:role/lectures-cloud 
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5174 
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - DELETE
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: false 

package:
  individually: true  

functions: 
  signUp:
    handler: functions/signUp/index.handler
    events:
      - httpApi:
          path: "/auth/signup"
          method: POST
  logIn:
    handler: functions/login/index.handler
    events:
      - httpApi:
          path: "/auth/login"
          method: POST
  requestResetPassword:
    handler: functions/requestResetPassword/index.handler
    events:
      - httpApi:
          path: "/auth/request-password-reset"
          method: POST
  resetPassword:
    handler: functions/resetPassword/index.handler
    events:
      - httpApi:
          path: "/auth/reset-password"
          method: POST
  verifyEmail:
    handler: functions/verifyEmail/index.handler
    events:
      - httpApi:
          path: "/auth/verify-email"
          method: GET                

resources: 
  Resources:
    usersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: agriaccount
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: resetToken
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ResetTokenIndex
            KeySchema:
              - AttributeName: resetToken
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST




