import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define a type for the slice state
interface SomeState {
  value: number;
}

// Define the initial state using that type
const initialState: SomeState = {
  value: 0,
};

export const someSlice = createSlice({
  name: 'someFeature',
  initialState,
  reducers: {
    increment: (state) => {
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
    incrementByAmount: (state, action: PayloadAction<number>) => {
      state.value += action.payload;
    },
  },
});

// Export the actions generated by createSlice
export const { increment, decrement, incrementByAmount } = someSlice.actions;

// Export the reducer to be added to the store
export default someSlice.reducer;
